use_frameworks!

platform :ios, '9.0'

target 'RxiStoreKit_Example' do
  pod 'RxiStoreKit', :path => '../'

  target 'RxiStoreKit_Tests' do
    inherit! :search_paths

    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Quick'
    pod 'Nimble'
  end
end
